#!/bin/env node
var argv = require('minimist')(process.argv.slice(2));

var configFile = argv.config || './settings.json';

var watcher = require('./lib/watcher');

var settings = require(configFile);

watcher.watch(settings);